---
- hosts: all
  sudo: true
  vars:
    web_server: nginx
  vars_files:
    - "vars/common.yml"
    - [ "vars/{{ web_server }}.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - { role: nginx, when: web_server == 'nginx' }
    - { role: php5-fpm, when: web_server == 'nginx' }
    - { role: apache, when: web_server == 'apache' }
    - { role: php5, when: web_server == 'apache' }
    - composer
    - phpcommon
    - app