tools:
    external_code_coverage:
        timeout: 300
    php_sim:
        enabled: true
        min_mass: 16
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
    php_analyzer:
        enabled: true
        extensions:
            - php
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
filter:
    excluded_paths:
        - 'app/*'
        - 'tests/*'
        - 'ansible/*'
        - 'web/*'
        - 'src/Phansible/Resources/ansible'
    paths: {  }
build_failure_conditions: {  }
