language: php
php:
   - 5.5
   - 5.6
before_install:
   - composer self-update
install:
   - composer install --no-interaction
   - php vendor/autoload.php
script:
   - mkdir -p build/logs
   - php vendor/bin/phpcs --standard=psr2 ./src
   - php vendor/bin/phpmd src/ text codesize,controversial,design,naming,unusedcode
   - php vendor/bin/phpunit
after_script:
   - php vendor/bin/coveralls
   ## Scrutinizer
   - wget https://scrutinizer-ci.com/ocular.phar
   - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
