phppackages:
  - php5-cli
  - php-pear
  - php5-curl
  - php5-imagick
  - php5-cgi
  - php5-common
  - php5-dbg
  - php5-enchant
  - php5-fpm
  - php5-gd
  - php5-geoip
  - php5-gmp
  - php5-imap
  - php5-interbase
  - php5-intl
  - php5-ldap
  - php5-mapscript
  - php5-mbstring
  - php5-mcrypt
  - php5-memcache
  - php5-memcached
  - php5-mysql
  - php5-odbc
  - php5-pspell
  - php5-readline
  - php5-recode
  - php5-snmp
  - php5-sqlite
  - php5-svn
  - php5-sybase
  - php5-tidy
  - php5-xcache
  - php5-xdebug
  - php5-xmlrpc
  - php5-xsl
  - php7.0-bz2
  - php7.0-cgi
  - php7.0-cli
  - php7.0-common
  - php7.0-curl
  - php7.0-dbg
  - php7.0-dev
  - php7.0-fpm
  - php7.0-gd
  - php7.0-imap
  - php7.0-interbase
  - php7.0-intl
  - php7.0-json
  - php7.0-ldap
  - php7.0-mcrypt
  - php7.0-modules-source
  - php7.0-mysql
  - php7.0-odbc
  - php7.0-opcache
  - php7.0-pgsql
  - php7.0-phpdbg
  - php7.0-pspell
  - php7.0-readline
  - php7.0-recode
  - php7.0-snmp
  - php7.0-sqlite3
  - php7.0-sybase
  - php7.0-tidy
  - php7.0-xmlrpc
