---
- hosts: webservers
  user: "{{ system_user }}"
  vars_prompt:
    - name: deploy_version
      default: master
      prompt: "Tag, Branch or Hash to deploy"
      private: no
  roles:
    - { role: app, tags: [ 'app' ] }
  tasks:
    - name: Set Maintenance Page
      shell: cp {{ doc_root }}/maintenance/maintenance.html {{ doc_root }}/maintenance.html
      ignore_errors: true

    - name: Checkout code
      git: repo=http://github.com/phansible/phansible.git dest={{ project_root }} accept_hostkey=true version={{ deploy_version }}

    - name: Self-update Composer
      become: yes
      shell: /usr/local/bin/composer self-update

    - name: Run Composer
      shell: /usr/local/bin/composer install --no-dev --no-progress chdir={{ project_root }}

    - name: Read ACLs for web_user
      become: yes
      shell: 'setfacl -Rn -m u:"{{ webserver_user }}":rX -m d:u:"{{ webserver_user }}":rX {{ project_root }}'

    - name: Read and Write ACLs for shell user
      become: yes
      shell: 'setfacl -Rn -m u:"{{ system_user }}":rwX -m d:u:"{{ system_user }}":rwX {{ project_root }}'

    - name: Make sure cache directory exists
      become: yes
      file: path={{ project_root }}/app/cache state=directory owner={{ system_user }} group={{ system_group }}

    - name: Clean cache directories
      become: yes
      file: path={{ project_root }}/app/cache/{{ item }} state=absent owner={{ system_user }} group={{ system_group }}
      with_items:
        - config
        - github-api-cache

    - name: Read and Write ACLs cache dir
      become: yes
      shell: 'setfacl -Rn -m u:"{{ webserver_user }}":rwX -m d:u:"{{ webserver_user }}":rwX {{ project_root }}'

    - name: Remove maintenance page
      file: path="{{ doc_root }}/maintenance.html" state=absent
